Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false
  config.ssh.insert_key = false
  config.ssh.forward_agent = true
  config.vm.provision "file", source: "~/.gitconfig", destination: ".gitconfig"

  config.vm.network "private_network", ip: "11.0.0.30"
  # Link the folder contatining all your code to /var/www of guest machine
  config.vm.synced_folder "~/code/", "/code"

  config.vm.provider :virtualbox do |vb|
    vb.memory = 2048
  end

  config.vm.provision "ansible" do |ansible|
  #  ansible.inventory_path="inventory"
    ansible.playbook = "provisioning/web.yml"
    ansible.inventory_path = "provisioning/hosts"
    ansible.limit = "vagrant_provision"
    ansible.verbose =  'v'
  end
